# Generated by Django 5.1 on 2024-08-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
