# Generated by Django 5.1 on 2024-12-20 20:11

import django.db.models.deletion
from django.db import migrations, models


def handle_null_orders(apps, schema_editor):
    OrderItem = apps.get_model("core", "OrderItem")
    # Eliminar las filas inválidas que tienen `order=None`
    OrderItem.objects.filter(order__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.RunPython(
            handle_null_orders
        ),  # Ejecutar la función antes de los cambios
        migrations.AddField(
            model_name="order",
            name="estado",
            field=models.CharField(
                choices=[
                    ("en_preparacion", "En Preparación"),
                    ("enviado", "Enviado"),
                    ("entregado", "Entregado"),
                ],
                default="en_preparacion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.order",
            ),
        ),
    ]
