# Generated by Django 5.1 on 2024-12-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_estado_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
