# Generated by Django 5.1 on 2024-12-24 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_menuitem_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='image_file',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
    ]
